parameters:
    fmm_app.broker.consumer_command: 
    fmm_app.broker.consumer_max_messages: 
    symfony_debug: 
    fmm_app.redirection_file: 
    fmm_app.trusted_proxies: 
    fmm_app.cold_storage.scheme: 
    fmm_app.solr.host: 
    fmm_app.console: 
    fmm_app.solr.port: 
    fmm_app.gateway.private.port: 80
    fmm_app.broker.vhost: 
    fmm_app.cors: [{"url": "http://admin.migrants.local.francemm.com", "credentials": "true", "methods": "GET, POST, PUT, PATCH, DELETE, OPTIONS", "headers": "Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With"}, {"url": "http://front.migrants.local.francemm.com", "credentials": "true", "methods": "GET, POST, PUT, PATCH, DELETE, OPTIONS", "headers": "Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With"}, {"url": "http://freeb.migrants.local.francemm.com", "credentials": "true", "methods": "GET, POST, PUT, PATCH, DELETE, OPTIONS", "headers": "Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With"}]
    fmm_app.database.host: postgresql
    fmm_app.path: /mnt/sources/migranium/migrants/apps/aggregator
    fmm_app.solr.timeout: 
    fmm_app.cold_storage.host: 
    fmm_app.name: aggregator
    fmm_app.proxy: 
    fmm_app.http_client.timeout: 30
    fmm_app.solr.path: 
    fmm_app.web.artifacts: web
    fmm_app.gateway.private.host: migrants.local.francemm.com
    fmm_app.gateway.public.scheme: http
    fmm_app.mailer.mail_to: 
    fmm_app.cold_storage.backup_path: 
    fmm_app.mailer.user: 
    fmm_app.cold_storage.replay_path: 
    fmm_app.database.test: True
    fmm_app.build_artifacts: 
    fmm_app.broker.password: 
    fmm_app.http.scheme: http
    fmm_app.broker.consumer_section: 
    fmm_app.fqname: application-migrants-aggregator
    fmm_app.gateway.private.scheme: http
    fmm_app.database.port: 5432
    fmm_app.broker.host: 
    fmm_app.mailer.transport: smtp
    fmm_app.broker.login: 
    fmm_app.database.user: maintain
    fmm_app.mailer.encryption: 
    fmm_app.mailer.host: localhost
    fmm_app.mailer.port: 
    fmm_app.http.port: 80
    fmm_app.gateway.public.host: migrants.local.francemm.com
    fmm_app.database.driver: pdo_pgsql
    fmm_app.jwt: False
    fmm_app.in_mem_store.uri: redis://redis
    fmm_app.jwt_acl: {"APPLICATION": {"^/aggregator/api/*": ["GET", "POST", "PUT", "DELETE", "PATCH"]}, "ROLE_JOURNALIST": {"^/aggregator/api/*": ["GET", "POST", "PUT", "DELETE", "PATCH"]}, "ANONYMOUS": {"^/aggregator/api/*": ["GET"]}, "ROLE_ADMIN": {"^/aggregator/api/*": ["GET", "POST", "PUT", "DELETE", "PATCH"]}, "ROLE_REM": {"^/aggregator/api/*": ["GET", "POST", "PUT", "DELETE", "PATCH"]}}
    fmm_app.database.name: migrants-aggregator
    fmm_app.mailer.password: 
    fmm_app.front.controller: app
    fmm_app.broker.consumer_queue: 
    fmm_app.broker.consumer_max_execution_time: 
    fmm_app.maintenance.path: 
    fmm_app.bf.server.id: 1cb8d2af-b9f4-4fa7-ae6a-f6d5b0a1b937
    fmm_app.gateway.public.port: 80
    fmm_app.monitoring.url: 
    fmm_app.solr.core: 
    fmm_app.forwarded: True
    fmm_app.server.name: aggregator.migrants.local.francemm.com
    fmm_app.http.host: aggregator.migrants.local.francemm.com
    fmm_app.broker.port: 
    symfony_env: 
    fmm_app.cold_storage.port: 
    fmm_app.bf.server.token: f29678587317f03ea4fe043169390889705f141debeb07d76739006bffd3baea
    fmm_app.mock.mode: 
    fmm_app.database.password: dave
    fmm_app.secret: aggregatormigrantsaggregatormigrantsaggregatormigrantsaggregatormigrants
    fmm_app.jwt_secret: Qekaf5Roz4XeSe0To4Qok6Uu
    fmm_app.mailer.mail_from: ~
    fmm_app.bam_activity_listener.enabled: False
