parameters:
    fmm_app.broker.consumer_command: swarrot:consume
    fmm_app.broker.consumer_max_messages: 50
    symfony_debug: 
    fmm_app.redirection_file: 
    fmm_app.trusted_proxies: 
    fmm_app.cold_storage.scheme: 
    fmm_app.solr.host: solr
    fmm_app.console: bin/console
    fmm_app.solr.port: 8983
    fmm_app.gateway.private.port: 80
    fmm_app.broker.vhost: /
    fmm_app.cors: False
    fmm_app.database.host: postgresql
    fmm_app.path: /mnt/sources/application/mezzo/apps/consumer
    fmm_app.solr.timeout: 5
    fmm_app.cold_storage.host: 
    fmm_app.name: consumer
    fmm_app.proxy: 
    fmm_app.http_client.timeout: 30
    fmm_app.solr.path: /solr
    fmm_app.web.artifacts: web
    fmm_app.gateway.private.host: mezzo.local.francemm.com
    fmm_app.gateway.public.scheme: http
    fmm_app.mailer.mail_to: charly.mezari@gmail.com
    fmm_app.cold_storage.backup_path: 
    fmm_app.mailer.user: fmm.test.notify@gmail.com
    fmm_app.cold_storage.replay_path: 
    fmm_app.database.test: 
    fmm_app.build_artifacts: build
    fmm_app.broker.password: test
    fmm_app.http.scheme: http
    fmm_app.broker.consumer_section: fmm_mezzo_consumer
    fmm_app.fqname: application-mezzo-consumer
    fmm_app.gateway.private.scheme: http
    fmm_app.database.port: 
    fmm_app.broker.host: rabbitmq
    fmm_app.mailer.transport: smtp
    fmm_app.broker.login: test
    fmm_app.database.user: 
    fmm_app.mailer.encryption: tls
    fmm_app.mailer.host: smtp.gmail.com
    fmm_app.mailer.port: 587
    fmm_app.http.port: 80
    fmm_app.gateway.public.host: mezzo.local.francemm.com
    fmm_app.database.driver: 
    fmm_app.jwt: ADMIN
    fmm_app.in_mem_store.uri: 
    fmm_app.jwt_acl: False
    fmm_app.database.name: 
    fmm_app.mailer.password: motdepassesecure
    fmm_app.front.controller: app
    fmm_app.broker.consumer_queue: fmm.content.f24 fmm.content.rfi fmm.content.mcd fmm.content.obs fmm.notify fmm.notify.push_batch fmm.score.f24 fmm.score.rfi fmm.score.mcd fmm.score.obs fmm.bam fmm.indexing
    fmm_app.broker.consumer_max_execution_time: 300
    fmm_app.maintenance.path: 
    fmm_app.bf.server.id: 1cb8d2af-b9f4-4fa7-ae6a-f6d5b0a1b937
    fmm_app.gateway.public.port: 80
    fmm_app.monitoring.url: 
    fmm_app.solr.core: mezzo
    fmm_app.forwarded: True
    fmm_app.server.name: consumer.mezzo.local.francemm.com
    fmm_app.http.host: consumer.mezzo.local.francemm.com
    fmm_app.broker.port: 5672
    symfony_env: dev
    fmm_app.cold_storage.port: 
    fmm_app.bf.server.token: f29678587317f03ea4fe043169390889705f141debeb07d76739006bffd3baea
    fmm_app.mock.mode: record
    fmm_app.database.password: 
    fmm_app.secret: consumerconsumerconsumerconsumerconsumerconsumer
    fmm_app.jwt_secret: Qekaf5Roz4XeSe0To4Qok6Uu
    fmm_app.mailer.mail_from: notify.fmm@gmail.com
    fmm_app.bam_activity_listener.enabled: True
